version: '3.8'

services:
  web:
    build: ./hello_world
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hello_world/:/hello_world/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_world
      - POSTGRES_PASSWORD=hello_world
      - POSTGRES_DB=hello_world_dev

volumes:
  postgres_data: